### ISSUE TITLE
Can't connect to JACK

### ISSUE THREAD

**Issue by davepinto** [Arkq/bluez-alsa#118]
I'm trying to get the bluez-alsa to route through jack as an output, so I can control which output I want to use more easily. alsa_out or zita-j2a segfaults whenever I try to bind the device to jack. Here is my asoundrc:

```
pcm.rawjack {
        type jack
                playback_ports {
                        0 system:playback_1;
                        1 system:playback_2;
                }
                capture_ports {
                        0 system:capture_1;
                        1 system:capture_2;
        }
}

pcm.jack {
        type plug
                slave { pcm "rawjack" }
        hint {
                description "JACK Audio Connection Kit";
        }
}

pcm.!default {
        type        plug;
        slave.pcm   "rawjack";
}

# bluetooth speaker
pcm.btspeaker {
 type plug
  slave {
    pcm {
      type          bluealsa;
      interface     hci0;
      device        70:26:05:2A:19:EA;
      profile       "a2dp";
    }
  }
  hint {
    show on;
    description "BT Headset";
  }
}

ctl.btspeaker {
        type        bluealsa;
        interface   "hci0"
}
```
This is how I'm running jack: `/usr/bin/jackd --sync -P 80 -p 1024 -d alsa -d hw:0 -n 3 -r 48000 -Xseq`
And this is the output of the command that keeps failing:
```
<main@david> ~ $ alsa_out -d btspeaker
WARNING: buffer size does not match: (requested 2048, got 9600)
WARNING: period size does not match: (requested 1024, got 1066)
Segmentation fault
<main@david> ~ $
```
Can anyone help me figure this out? Thank you.

**Comment by davepinto** [comment]
Nevermind, found the similar issue, and got it working. It's still unusable though due to overflow/underflow causing stuttering, extreme lag, and an eventual disconnect.

**Comment by sdfg2** [comment]
Could you explain what you did?  I'm trying to do this myself, and getting nowhere.  If I use `-j extra_device` it segfaults.  Without that, I get a DBus error `Oct 01 13:25:31 mymachine bluealsa[20016]: /usr/bin/bluealsa: Couldn't acquire transport: GDBus.Error:org.bluez.Error.NotAuthorized: Operation Not Authorized`.  I've already explored an alsa method (create new pcm, type multi, slave and bind the outputs), which works using aplay -D, but fails on alsa->pulseaudio and alsa->pulseaudio->jack (I only hear from the 'proper' speakers).  If I had any hair left I'd be pulling it out by this point. (Not to mention that cadence doesn't list non-hw devices :( )

**Comment by infirit** [comment]
Permission problems are likely due to not being the correct group. By default only root is allowed to connect to the BlueZ dbus interfaces, see ``/etc/dbus-1/system.d/bluetooth.conf`` which group you need to be in, for me it is plugdev.

Also, pulseaudio and bluealsa do not mix well. Have you seen https://github.com/Arkq/bluez-alsa#troubleshooting which deals with this?

**Comment by sdfg2** [comment]
I already tried copying the org.bluez permission that are in the root section to apply to `group="audio"`.

That gives me `Oct 03 17:38:37 artemis bluealsa[20016]: /usr/bin/bluealsa: Couldn't acquire transport: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Method "Acquire" with signature "" on interface "org.bluez.MediaTransport1" doesn't exist`.

Can we get a section in the troubleshooting for these dbus issues please?

(As for the pulseaudio and bluealsa not mixing, that's not relevant to this issue, but to allay your curiosity, yes, that's sorted.  I would be able to get audio out of the bluetooth speakers using `aplay -D` otherwise ;) bluealsa has control)

**Comment by infirit** [comment]
>GDBus.Error:org.freedesktop.DBus.Error.UnknownObject

BlueZ needs to be installed and running, the above indicates that dbus is not able to find the the BlueZ dbus objects. Is it installed and running? As a test does it work as root?

>Can we get a section in the troubleshooting for these dbus issues please?

There is a wiki page that anyone can open a PR for https://github.com/Arkq/bluez-alsa/wiki

>but to allay your curiosity

I don't use jack and don't care about it. You could just have said "I know, sorted" instead of acting like smart ass. Good luck with getting bluealsa to work with jack.

**Comment by sdfg2** [comment]
@infirit I'm sorry, I didn't mean to seem like a smart ass.

I'm working with someone on another thread about this, we're starting to put together a step-by-step thing as we work stuff out, I'll make sure we add it to the wiki after.

Also yes, thank you for the hint about bluez.  All the dbus messages I was getting were because it wasn't responding in some way.  I'm not sure what, how, or why, but a reboot fixed it.  I was consistently getting segfaults like everyone else.

But, I did manage to make some progress.  #147
