### ISSUE TITLE
Synching audio playback with another hardware device

### ISSUE THREAD

**Issue by mshkrebtan** [Arkq/bluez-alsa#127]
Hi @Arkq and guys!

First of all, thank you for creating such a great ALSA backend!

I have successfully set up bluez-alsa and made my Bluetooth speaker a secondary output for my MPD server:
```
audio_output {
  type "alsa"
  name "Denon Envaya"
  mixer_type "hardware"
  replay_gain_handler "none"

  device "bluealsa:HCI=hci0,DEV=04:FE:A1:EF:EC:FA,PROFILE=a2dp"
  auto_resample "no"
  auto_channels "no"
  auto_format "yes"
  allowed_formats "48000:16:* 44100:16:*"

  mixer_device "bluealsa"
  mixer_control "Denon Envaya - A2DP"
  mixer_index "0"
}
```

The primary output is a USB DAC and configured similarly:
```
audio_output {
  type "alsa"
  name "Arcam irDAC-II"
  mixer_type "hardware"
  replay_gain_handler "none"

  device "hw:1,0"
  auto_resample "no"
  auto_channels "no"
  auto_format "no"
  dop "yes"

  mixer_device "hw:1"
  mixer_control "irDAC II "
  mixer_index "0"
}
```

Unfortunately, when I play music with both outputs enabled, I hear the Bluetooth speaker (the "Denon Envaya" output) drift out of synchronization. What helps is disabling the "Denon Envaya" output and then enabling it back.

Does someone know how to permanently fix the issue?

Thanks!

**Comment by borine** [comment]
I realize this issue has remained unanswered for nearly 3 years now, so describing this comment as "late to the party" is an extreme understatement!

MPD makes no attempt to synchronize its outputs. Bluetooth devices run at a clock rate determined by the bluetooth controller - this is necessary because the frequency-hopping design of bluetooth requires all connected devices to operate to the same clock within very tight tolerances. The USB DAC is clocked by the USB bus. If there is a significant drift between the two clocks then noticable drift in the audio is inevitable.  I think that, unfortunately , there is no workaround for that. 

I'm closing this now as I do not believe that there is anything that bluez-alsa can do about it. Please re-open if you wish to add any new information,
