### ISSUE TITLE
mpg123 stuck in prepare/start/underrun/prepare/start/underrun infinite cycle

### ISSUE THREAD

**Issue by borine** [Arkq/bluez-alsa#247]
Certain mp3 files cause mpg123 with bluealsa output to enter an infinite cycle of underruns as soon as mpg123 begins playback:
```
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred
```
I have a default install built from the latest bluealsa sources.
I've found that files whose sample rate match the bluetooth a2dp rate hit this problem, files at other rates work OK. So if the alsa plug invokes resampling everything is fine, if the plug passes the stream directly to bluealsa then it fails as above.

Looking through the mpg123 source code I see that in the sw params it sets start_threshold to just 1 frame. When writing the first chunk of audio it writes less than a full period of frames.
Seeing this, I would absolutely expect an immediate underrun, since the very first frame written starts the pcm processing, but it has less than the necessary 1 period to process.

However, using a hardware device, there are no underruns. It seems as if hardware drivers take the start_threshold as a "permission" to start rather than a "command" to start. So they report no errors until after the first period has been written.

The alsa docs are not clear on which is correct here. The ioplug code always calls the start() function of the underlying software plugin when start_threshold is reached, and that is why bluealsa always tries to process the first write from mpg123 and always encounters the underrun. So I guess there is a decision to be made - should bluealsa always honour the start() call from ioplug, or should it try harder to behave like a hardware device and suppress underrun errors until the first period is reached?

In the strictest sense, I think this is a bug in mpg123. It just makes no sense to set a start theshold of less than 1 period. But mpg123 has always done this, with no problem from any alsa device except bluealsa. 

If you think bluealsa should accommodate this "quirk" of mpg123, then I can start to look at producing a PR, but I  don't want to spend time on it if you believe bluealsa is correct to differ from hw in this case.

**Comment by Arkq** [comment]
> Looking through the mpg123 source code I see that in the sw params it sets start_threshold to just 1 frame. When writing the first chunk of audio it writes less than a full period of frames. Seeing this, I would absolutely expect an immediate underrun, since the very first frame written starts the pcm processing, but it has less than the necessary 1 period to process.

Maybe the `PCM is automatically started when playback frames available to PCM are >= threshold` from the doc can be interpreted as "PCM will start when it feels right, but NOT before threshold". So, then you are right that there is a need to add some logic to bluealsa PCM plug-in.

I'm not entirely sure how to achieve that without busy waiting with current PCM plug-in architecture. There is the IO thread which acts as a hardware ring buffer, but there is no possibility to be signaled that particular number of bytes is available. In order to know when the `snd_pcm_write()` has been called, one shall implement `transfer` callback. I though about rewriting PCM plug-in but currently there are other more important areas of bluez-alsa which need some attention. During my initial draft of bluez-alsa, the PCM plug-in was based on `transfer` callback, however due to synchronization problems I've switched to IO thread approach. Right now the synchronization issues should be resolved by sending PCM file descriptor via UNIX socket (in the PoC I've shared FIFO via named pipe, which had to be opened in a right order). Also, the `transfer` approach seems to be tested better, because most PCM plug-ins use it (bluealsa is somehow different in this aspect which causes troubles and patches I've proposed have not been merged or reviewed by ALSA maintainers).

If you think that it will be possible to delay IO start (without busy waiting) until full period is available, I'm OK with that.
