### ISSUE TITLE
What is --enable-aac use case

### ISSUE THREAD

**Issue by roizcorp** [Arkq/bluez-alsa#254]
Hi,

I'm trying to understand what would be useful for by using aac?
(sorry if the answer is obvious)

**Comment by Arkq** [comment]
Better audio quality with iPhone :) and headsets dedicated for iPhone (with
AAC support but not aptx nor ldac).

**Comment by roizcorp** [comment]
so why it is mentioned in the default build guide? (I'm using android)
any other"--enable-XXX" option you would recommend?

**Comment by Arkq** [comment]
Because it's the only extra codec which works out of the box with bluealsa and provides encoder and decoder. It works with iPhone and some android phones so it covers almost all cases for sink. Also, it was the first codec available with this project, so it is explicitly mentioned in the build section.

**Comment by roizcorp** [comment]
cool, I already built fdk-aac for it...so I will include it in, sounds great BTW
can it make the phone as the speaker? (considering the other side is the source for sound?)
