### ISSUE TITLE
Testing speaker/audio sink

### ISSUE THREAD

**Issue by ashah7** [Arkq/bluez-alsa#307]
Is there a way to test if the Bluetooth device is connected and will work with bluealsa?
For example in pulseaudio one can run 
`pactl list sinks short`
to display connected devices, at that point you know its all connected and capable to play.
This is different to just running Bluetooth commands like
`hcitool con `
which tell you the device is connected via Bluetooth.
The examples provided verify using aplay and actually playing

**Comment by graham8** [comment]
aplay -L | grep bluealsa

**Comment by graham8** [comment]
try amixer -D bluealsa

**Comment by Arkq** [comment]
Using `amixer` (as @graham8 has suggested) should result in a good estimate whether BT device is connected and will work with BlueALSA. Better approach is to use BlueALSA B-Bus API (which is internally used by `amixer`), because `amixer` might not show all devices. E.g. `amixer` will not show HFP capable device with codec selection support if first call has not been made yet.

To query for all connected BT devices use something as follows:
```
gdbus call --system -d org.bluealsa -o /org/bluealsa -m org.bluealsa.Manager1.GetPCMs
```
