### ISSUE TITLE
sco acquistion failure not handled

### ISSUE THREAD

**Issue by borine** [Arkq/bluez-alsa#315]
Sometimes, when a client opens a sco pcm for playback on an AG instance, transport acquisition can fail. This failure is ignored by the sco io thread, so the client becomes blocked writing to a full pipe that the server never reads from. At the very least, the client pcm should be closed when no transport can be acquired (the a2dp code does this).

I can trigger this by first starting an a2dp playback client, then starting a sco playback client to the same device (using `bluealsa -p a2dp-source -p hfp-ag`). Once this has happened with my device, all future sco attempts fail, even after the a2dp transport has been released. Disconnecting the device then reconnecting restores normal function.

**Comment by borine** [comment]
I'm unable to reproduce the acquisition failure today. The connect() call was failing with ECONNABORTED which bluez maps from HCI error 0x16 "Connection terminated by local host", but whatever was causing it has corrected itself now :(
I think the issue is still valid, but just very hard to deliberately trigger.

**Comment by Arkq** [comment]
I think that this issue is real. Sometimes, I've also experienced such behavior.... It was when I was mostly focused on HFP - I've run a lot of "tests". And I remember that from time to time bluealsa server got stuck until BT device reconnection or what worst bluealsa server restart.... I will look at this, but rather in a distant future :|
