### ISSUE TITLE
Extend Readme with information to bluealsa github

### ISSUE THREAD

**Issue by J-u-n-o** [Arkq/bluez-alsa#331]
Took some analyzing, but would be nice the introduction links to the related github
https://github.com/raspberrypi-ui/bluealsa,
and also back to itself (https://github.com/Arkq/bluez-alsa), 
this to see the relation between them.

**Comment by Arkq** [comment]
There are potentially other forks of this project (some private, some public), linking to all of them seems to be pointless. The problem is that the fork (or maybe clone) on the raspberrypi-up organization was not made with the "fork" button, and GitHub does not show it as fork (which would allow to see a dff between them).
