### ISSUE TITLE
BLE MIDI profile based on alsa sequencer

### ISSUE THREAD

**Issue by RadekPolyend** [Arkq/bluez-alsa#564]
Hello, have you considered implementing MIDI BLE profile using alsa sequencer so that there will be a possibility to use virtual midi keyboards. I've been able to make it work using pygattmidi and python-rtmidi but having it directly in alsa plugin seemed to be much better option. If someone guide me through the bluez-alsa code concept I might do it by my own.

**Comment by Arkq** [comment]
No, I have not been considering that. However, that might be a good addition to the project. I will have to research this topic to know whether bluez-alsa is indeed a good place for that.

I've been trying to look at projects you have mentioned. But I was not able to find pygattmidi source. Could you post links to those projects?

**Comment by RadekPolyend** [comment]
https://github.com/NullMember/PyMIDIGATT- I've modified example.py by adding forwarding packets to alsa sequencer using python-rtmidi and made it work.
Currently bluez supports only client side of BLE over MIDI but there is a lack of server implementation. In bluez5 there is gatt-server example tool which might be a baseline for implementation to register midi gatt service and adding forwarding of midi packets to alsa sequencer. bluez-alsa sounds like a ideal place for that to me although new tool might be added in bluez as well.

**Comment by arkq** [comment]
Since commit https://github.com/arkq/bluez-alsa/commit/e35ddaf62bf1b45331cecc9309808360cdc8f435 there is a built-in suport for BLE MIDI service in BlueALSA. There is no D-Bus dependency on the MIDI client. It can connect to external MIDI BLE device in the same way as it would connect to a local MIDI card.

The MIDI suport is activated by enabling MIDI profile, i.e.:  `bluealsa -p midi` Then, one can access connected BLE MIDI via:

```
pi@rpi:~ $ aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
128:0    BlueALSA                         BLE MIDI Server
```

As for now, the MIDI support is not ideal, but I'll try to finish that in the nearest future (e.g.: proper BLE MIDI timing is not implemented yet). Also, there is no BLE advertising built-in, so in order to let other know that the BLE MIDI service is there, one has to do it manually, e.g.:

```
bluetoothctl
# menu advertise
# uuids 03B80E5A-EDE8-4B33-A751-6CE34EC4C700
# name 'BLE MIDI Server'
# discoverable on
# back
# advertise peripheral
```
