### ISSUE TITLE
Can't detect libsystemd-dev on debian trixie

### ISSUE THREAD

**Issue by sergey-suloev** [arkq/bluez-alsa#716]
The build script can't detect libsystemd-dev while compiling on debian trixie. 
This is probably because the version format includes "~rc", see here https://packages.debian.org/trixie/libsystemd-dev

**Comment by arkq** [comment]
I think that maybe that should be reported to Debian (or autotools...) since bluez-alsa is not the only project which checks for systemd version with autotools. Quick search shows other projects potentially affected by that: https://sourcegraph.com/search?q=context:global+%22PKG_CHECK_MODULES%28%5BSYSTEMD%5D%2C+%5Bsystemd+%3E%3D%22&patternType=keyword&sm=0

**Comment by sergey-suloev** [comment]
ok, as soon as you use system-provided tools to detect the library then we can close it here
